type Theme = {
  id: string;
  name: string;
  isDark: boolean;
  accentColor: string;
};

const THEMES: Theme[] = [
  { id: "typehere-dark", name: "Type Here", isDark: true, accentColor: "#a78bfa" },
  { id: "light", name: "Light", isDark: false, accentColor: "#666666" },
  { id: "paper", name: "Paper", isDark: false, accentColor: "#7a6e61" },
  { id: "sepia", name: "Sepia", isDark: false, accentColor: "#7a6b57" },
  { id: "dark", name: "Dark", isDark: true, accentColor: "#a1a1aa" },
  { id: "0x96f", name: "0x96f", isDark: true, accentColor: "#00cde8" },
  { id: "12-bit-rainbow", name: "12-bit Rainbow", isDark: true, accentColor: "#3060b0" },
  { id: "3024-day", name: "3024 Day", isDark: false, accentColor: "#01a0e4" },
  { id: "3024-night", name: "3024 Night", isDark: true, accentColor: "#01a0e4" },
  { id: "aardvark-blue", name: "Aardvark Blue", isDark: true, accentColor: "#1370d3" },
  { id: "abernathy", name: "Abernathy", isDark: true, accentColor: "#1093f5" },
  { id: "adventure", name: "Adventure", isDark: true, accentColor: "#417ab3" },
  { id: "adventure-time", name: "Adventure Time", isDark: true, accentColor: "#0f4ac6" },
  { id: "adwaita", name: "Adwaita", isDark: false, accentColor: "#1e78e4" },
  { id: "adwaita-dark", name: "Adwaita Dark", isDark: true, accentColor: "#1e78e4" },
  { id: "afterglow", name: "Afterglow", isDark: true, accentColor: "#6c99bb" },
  { id: "alabaster", name: "Alabaster", isDark: false, accentColor: "#325cc0" },
  { id: "alien-blood", name: "Alien Blood", isDark: true, accentColor: "#2f6a7f" },
  { id: "andromeda", name: "Andromeda", isDark: true, accentColor: "#2472c8" },
  { id: "apple-classic", name: "Apple Classic", isDark: true, accentColor: "#1c3fe1" },
  { id: "apple-system-colors", name: "Apple System Colors", isDark: true, accentColor: "#0869cb" },
  { id: "apple-system-colors-light", name: "Apple System Colors Light", isDark: false, accentColor: "#0869cb" },
  { id: "arcoiris", name: "Arcoiris", isDark: true, accentColor: "#518bfc" },
  { id: "ardoise", name: "Ardoise", isDark: true, accentColor: "#2465c2" },
  { id: "argonaut", name: "Argonaut", isDark: true, accentColor: "#008df8" },
  { id: "arthur", name: "Arthur", isDark: true, accentColor: "#6495ed" },
  { id: "atelier-sulphurpool", name: "Atelier Sulphurpool", isDark: true, accentColor: "#3d8fd1" },
  { id: "atom", name: "Atom", isDark: true, accentColor: "#85befd" },
  { id: "atom-one-dark", name: "Atom One Dark", isDark: true, accentColor: "#61afef" },
  { id: "atom-one-light", name: "Atom One Light", isDark: false, accentColor: "#2f5af3" },
  { id: "aura", name: "Aura", isDark: true, accentColor: "#a277ff" },
  { id: "aurora", name: "Aurora", isDark: true, accentColor: "#102ee4" },
  { id: "ayu", name: "Ayu", isDark: true, accentColor: "#53bdfa" },
  { id: "ayu-light", name: "Ayu Light", isDark: false, accentColor: "#3199e1" },
  { id: "ayu-mirage", name: "Ayu Mirage", isDark: true, accentColor: "#6dcbfa" },
  { id: "banana-blueberry", name: "Banana Blueberry", isDark: true, accentColor: "#22e8df" },
  { id: "batman", name: "Batman", isDark: true, accentColor: "#737174" },
  { id: "belafonte-day", name: "Belafonte Day", isDark: false, accentColor: "#426a79" },
  { id: "belafonte-night", name: "Belafonte Night", isDark: true, accentColor: "#426a79" },
  { id: "birds-of-paradise", name: "Birds Of Paradise", isDark: true, accentColor: "#5a86ad" },
  { id: "black-metal", name: "Black Metal", isDark: true, accentColor: "#888888" },
  { id: "black-metal-bathory", name: "Black Metal (Bathory)", isDark: true, accentColor: "#888888" },
  { id: "black-metal-burzum", name: "Black Metal (Burzum)", isDark: true, accentColor: "#888888" },
  { id: "black-metal-dark-funeral", name: "Black Metal (Dark Funeral)", isDark: true, accentColor: "#888888" },
  { id: "black-metal-gorgoroth", name: "Black Metal (Gorgoroth)", isDark: true, accentColor: "#888888" },
  { id: "black-metal-immortal", name: "Black Metal (Immortal)", isDark: true, accentColor: "#888888" },
  { id: "black-metal-khold", name: "Black Metal (Khold)", isDark: true, accentColor: "#888888" },
  { id: "black-metal-marduk", name: "Black Metal (Marduk)", isDark: true, accentColor: "#888888" },
  { id: "black-metal-mayhem", name: "Black Metal (Mayhem)", isDark: true, accentColor: "#888888" },
  { id: "black-metal-nile", name: "Black Metal (Nile)", isDark: true, accentColor: "#888888" },
  { id: "black-metal-venom", name: "Black Metal (Venom)", isDark: true, accentColor: "#888888" },
  { id: "blazer", name: "Blazer", isDark: true, accentColor: "#7a7ab8" },
  { id: "blue-berry-pie", name: "Blue Berry Pie", isDark: true, accentColor: "#90a5bd" },
  { id: "blue-dolphin", name: "Blue Dolphin", isDark: true, accentColor: "#82aaff" },
  { id: "blue-matrix", name: "Blue Matrix", isDark: true, accentColor: "#00b0ff" },
  { id: "bluloco-dark", name: "Bluloco Dark", isDark: true, accentColor: "#3476ff" },
  { id: "bluloco-light", name: "Bluloco Light", isDark: false, accentColor: "#275fe4" },
  { id: "borland", name: "Borland", isDark: true, accentColor: "#96cbfe" },
  { id: "box", name: "Box", isDark: true, accentColor: "#0d73cc" },
  { id: "breadog", name: "Breadog", isDark: false, accentColor: "#005cb4" },
  { id: "breeze", name: "Breeze", isDark: true, accentColor: "#1d99f3" },
  { id: "bright-lights", name: "Bright Lights", isDark: true, accentColor: "#76d4ff" },
  { id: "broadcast", name: "Broadcast", isDark: true, accentColor: "#6d9cbe" },
  { id: "brogrammer", name: "Brogrammer", isDark: true, accentColor: "#2a84d2" },
  { id: "builtin-dark", name: "Builtin Dark", isDark: true, accentColor: "#0d0dc8" },
  { id: "builtin-light", name: "Builtin Light", isDark: false, accentColor: "#0000bb" },
  { id: "builtin-pastel-dark", name: "Builtin Pastel Dark", isDark: true, accentColor: "#96cbfe" },
  { id: "builtin-solarized-dark", name: "Builtin Solarized Dark", isDark: true, accentColor: "#268bd2" },
  { id: "builtin-solarized-light", name: "Builtin Solarized Light", isDark: false, accentColor: "#268bd2" },
  { id: "builtin-tango-dark", name: "Builtin Tango Dark", isDark: true, accentColor: "#3465a4" },
  { id: "builtin-tango-light", name: "Builtin Tango Light", isDark: false, accentColor: "#3465a4" },
  { id: "c64", name: "C64", isDark: true, accentColor: "#6657b3" },
  { id: "cga", name: "CGA", isDark: true, accentColor: "#0d0db7" },
  { id: "clrs", name: "CLRS", isDark: false, accentColor: "#135cd0" },
  { id: "calamity", name: "Calamity", isDark: true, accentColor: "#3b79c7" },
  { id: "carbonfox", name: "Carbonfox", isDark: true, accentColor: "#78a9ff" },
  { id: "catppuccin-frappe", name: "Catppuccin Frappe", isDark: true, accentColor: "#8caaee" },
  { id: "catppuccin-latte", name: "Catppuccin Latte", isDark: false, accentColor: "#1e66f5" },
  { id: "catppuccin-macchiato", name: "Catppuccin Macchiato", isDark: true, accentColor: "#8aadf4" },
  { id: "catppuccin-mocha", name: "Catppuccin Mocha", isDark: true, accentColor: "#89b4fa" },
  { id: "chalk", name: "Chalk", isDark: true, accentColor: "#2a7fac" },
  { id: "chalkboard", name: "Chalkboard", isDark: true, accentColor: "#7372c3" },
  { id: "challenger-deep", name: "Challenger Deep", isDark: true, accentColor: "#65b2ff" },
  { id: "chester", name: "Chester", isDark: true, accentColor: "#288ad6" },
  { id: "ciapre", name: "Ciapre", isDark: true, accentColor: "#576d8c" },
  { id: "citruszest", name: "Citruszest", isDark: true, accentColor: "#00bfff" },
  { id: "cobalt-neon", name: "Cobalt Neon", isDark: true, accentColor: "#8ff586" },
  { id: "cobalt-next", name: "Cobalt Next", isDark: true, accentColor: "#409dd4" },
  { id: "cobalt-next-dark", name: "Cobalt Next Dark", isDark: true, accentColor: "#409dd4" },
  { id: "cobalt-next-minimal", name: "Cobalt Next Minimal", isDark: true, accentColor: "#409dd4" },
  { id: "cobalt2", name: "Cobalt2", isDark: true, accentColor: "#1460d2" },
  { id: "coffee-theme", name: "Coffee Theme", isDark: false, accentColor: "#0225c7" },
  { id: "crayon-pony-fish", name: "Crayon Pony Fish", isDark: true, accentColor: "#8c87b0" },
  { id: "cursor-dark", name: "Cursor Dark", isDark: true, accentColor: "#81a1c1" },
  { id: "cutie-pro", name: "Cutie Pro", isDark: true, accentColor: "#42d9c5" },
  { id: "cyberdyne", name: "Cyberdyne", isDark: true, accentColor: "#0071cf" },
  { id: "cyberpunk", name: "Cyberpunk", isDark: true, accentColor: "#00bfff" },
  { id: "cyberpunk-scarlet-protocol", name: "Cyberpunk Scarlet Protocol", isDark: true, accentColor: "#0271b6" },
  { id: "dark-modern", name: "Dark Modern", isDark: true, accentColor: "#0078d4" },
  { id: "dark-pastel", name: "Dark Pastel", isDark: true, accentColor: "#5555ff" },
  { id: "dark-plus", name: "Dark+", isDark: true, accentColor: "#2472c8" },
  { id: "darkermatrix", name: "Darkermatrix", isDark: true, accentColor: "#00cb6b" },
  { id: "darkmatrix", name: "Darkmatrix", isDark: true, accentColor: "#2c9a84" },
  { id: "darkside", name: "Darkside", isDark: true, accentColor: "#1c98e8" },
  { id: "dawnfox", name: "Dawnfox", isDark: false, accentColor: "#286983" },
  { id: "dayfox", name: "Dayfox", isDark: false, accentColor: "#2848a9" },
  { id: "deep", name: "Deep", isDark: true, accentColor: "#5665ff" },
  { id: "desert", name: "Desert", isDark: true, accentColor: "#cd853f" },
  { id: "detuned", name: "Detuned", isDark: true, accentColor: "#0094d9" },
  { id: "dimidium", name: "Dimidium", isDark: true, accentColor: "#0575d8" },
  { id: "dimmed-monokai", name: "Dimmed Monokai", isDark: true, accentColor: "#4f76a1" },
  { id: "django", name: "Django", isDark: true, accentColor: "#315d3f" },
  { id: "django-reborn-again", name: "Django Reborn Again", isDark: true, accentColor: "#245032" },
  { id: "django-smooth", name: "Django Smooth", isDark: true, accentColor: "#989898" },
  { id: "doom-one", name: "Doom One", isDark: true, accentColor: "#a9a1e1" },
  { id: "doom-peacock", name: "Doom Peacock", isDark: true, accentColor: "#2a6cc6" },
  { id: "dot-gov", name: "Dot Gov", isDark: true, accentColor: "#17b2e0" },
  { id: "dracula", name: "Dracula", isDark: true, accentColor: "#bd93f9" },
  { id: "dracula-plus", name: "Dracula+", isDark: true, accentColor: "#82aaff" },
  { id: "duckbones", name: "Duckbones", isDark: true, accentColor: "#00a3cb" },
  { id: "duotone-dark", name: "Duotone Dark", isDark: true, accentColor: "#ffc284" },
  { id: "duskfox", name: "Duskfox", isDark: true, accentColor: "#569fba" },
  { id: "encom", name: "ENCOM", isDark: true, accentColor: "#0081ff" },
  { id: "earthsong", name: "Earthsong", isDark: true, accentColor: "#1398b9" },
  { id: "electron-highlighter", name: "Electron Highlighter", isDark: true, accentColor: "#77abff" },
  { id: "elegant", name: "Elegant", isDark: true, accentColor: "#8dabe1" },
  { id: "elemental", name: "Elemental", isDark: true, accentColor: "#497f7d" },
  { id: "elementary", name: "Elementary", isDark: true, accentColor: "#124799" },
  { id: "embark", name: "Embark", isDark: true, accentColor: "#57c7ff" },
  { id: "embers-dark", name: "Embers Dark", isDark: true, accentColor: "#6d5782" },
  { id: "espresso", name: "Espresso", isDark: true, accentColor: "#6c99bb" },
  { id: "espresso-libre", name: "Espresso Libre", isDark: true, accentColor: "#0066ff" },
  { id: "everblush", name: "Everblush", isDark: true, accentColor: "#67b0e8" },
  { id: "everforest-dark-hard", name: "Everforest Dark Hard", isDark: true, accentColor: "#7fbbb3" },
  { id: "everforest-light-med", name: "Everforest Light Med", isDark: false, accentColor: "#7fbbb3" },
  { id: "fahrenheit", name: "Fahrenheit", isDark: true, accentColor: "#7f0e0e" },
  { id: "fairyfloss", name: "Fairyfloss", isDark: true, accentColor: "#c2ffdf" },
  { id: "farmhouse-dark", name: "Farmhouse Dark", isDark: true, accentColor: "#0049e6" },
  { id: "farmhouse-light", name: "Farmhouse Light", isDark: false, accentColor: "#092ccd" },
  { id: "fideloper", name: "Fideloper", isDark: true, accentColor: "#2e78c2" },
  { id: "firefly-traditional", name: "Firefly Traditional", isDark: true, accentColor: "#5a63ff" },
  { id: "firefox-dev", name: "Firefox Dev", isDark: true, accentColor: "#359ddf" },
  { id: "firewatch", name: "Firewatch", isDark: true, accentColor: "#4d89c4" },
  { id: "fish-tank", name: "Fish Tank", isDark: true, accentColor: "#525fb8" },
  { id: "flat", name: "Flat", isDark: true, accentColor: "#3167ac" },
  { id: "flatland", name: "Flatland", isDark: true, accentColor: "#5096be" },
  { id: "flexoki-dark", name: "Flexoki Dark", isDark: true, accentColor: "#4385be" },
  { id: "flexoki-light", name: "Flexoki Light", isDark: false, accentColor: "#205ea6" },
  { id: "floraverse", name: "Floraverse", isDark: true, accentColor: "#1d6da1" },
  { id: "forest-blue", name: "Forest Blue", isDark: true, accentColor: "#8ed0ce" },
  { id: "framer", name: "Framer", isDark: true, accentColor: "#00aaff" },
  { id: "front-end-delight", name: "Front End Delight", isDark: true, accentColor: "#2c70b7" },
  { id: "fun-forrest", name: "Fun Forrest", isDark: true, accentColor: "#4699a3" },
  { id: "galaxy", name: "Galaxy", isDark: true, accentColor: "#589df6" },
  { id: "galizur", name: "Galizur", isDark: true, accentColor: "#2255cc" },
  { id: "ghostty-default-style-dark", name: "Ghostty Default Style Dark", isDark: true, accentColor: "#82a2be" },
  { id: "github", name: "GitHub", isDark: false, accentColor: "#003e8a" },
  { id: "github-dark", name: "GitHub Dark", isDark: true, accentColor: "#6ca4f8" },
  { id: "github-dark-colorblind", name: "GitHub Dark Colorblind", isDark: true, accentColor: "#58a6ff" },
  { id: "github-dark-default", name: "GitHub Dark Default", isDark: true, accentColor: "#58a6ff" },
  { id: "github-dark-dimmed", name: "GitHub Dark Dimmed", isDark: true, accentColor: "#539bf5" },
  { id: "github-dark-high-contrast", name: "GitHub Dark High Contrast", isDark: true, accentColor: "#71b7ff" },
  { id: "github-light-colorblind", name: "GitHub Light Colorblind", isDark: false, accentColor: "#0969da" },
  { id: "github-light-default", name: "GitHub Light Default", isDark: false, accentColor: "#0969da" },
  { id: "github-light-high-contrast", name: "GitHub Light High Contrast", isDark: false, accentColor: "#0349b4" },
  { id: "gitlab-dark", name: "GitLab Dark", isDark: true, accentColor: "#7fb6ed" },
  { id: "gitlab-dark-grey", name: "GitLab Dark Grey", isDark: true, accentColor: "#7fb6ed" },
  { id: "gitlab-light", name: "GitLab Light", isDark: false, accentColor: "#006cd8" },
  { id: "glacier", name: "Glacier", isDark: true, accentColor: "#1f5872" },
  { id: "grape", name: "Grape", isDark: true, accentColor: "#487df4" },
  { id: "grass", name: "Grass", isDark: true, accentColor: "#0000a3" },
  { id: "grey-green", name: "Grey Green", isDark: true, accentColor: "#00deff" },
  { id: "gruber-darker", name: "Gruber Darker", isDark: true, accentColor: "#92a7cb" },
  { id: "gruvbox-dark", name: "Gruvbox Dark", isDark: true, accentColor: "#458588" },
  { id: "gruvbox-dark-hard", name: "Gruvbox Dark Hard", isDark: true, accentColor: "#458588" },
  { id: "gruvbox-light", name: "Gruvbox Light", isDark: false, accentColor: "#458588" },
  { id: "gruvbox-light-hard", name: "Gruvbox Light Hard", isDark: false, accentColor: "#458588" },
  { id: "gruvbox-material", name: "Gruvbox Material", isDark: true, accentColor: "#6da3ec" },
  { id: "gruvbox-material-dark", name: "Gruvbox Material Dark", isDark: true, accentColor: "#7daea3" },
  { id: "gruvbox-material-light", name: "Gruvbox Material Light", isDark: false, accentColor: "#45707a" },
  { id: "guezwhoz", name: "Guezwhoz", isDark: true, accentColor: "#5aa0d6" },
  { id: "hax0r-blue", name: "HaX0R Blue", isDark: true, accentColor: "#10b6ff" },
  { id: "hax0r-gr33n", name: "HaX0R Gr33N", isDark: true, accentColor: "#15d00d" },
  { id: "hax0r-r3d", name: "HaX0R R3D", isDark: true, accentColor: "#b00d0d" },
  { id: "hacktober", name: "Hacktober", isDark: true, accentColor: "#206ec5" },
  { id: "hardcore", name: "Hardcore", isDark: true, accentColor: "#66d9ef" },
  { id: "harper", name: "Harper", isDark: true, accentColor: "#489e48" },
  { id: "havn-daggry", name: "Havn Daggry", isDark: false, accentColor: "#3a577d" },
  { id: "havn-skumring", name: "Havn Skumring", isDark: true, accentColor: "#596cf7" },
  { id: "heeler", name: "Heeler", isDark: true, accentColor: "#5ba5f2" },
  { id: "highway", name: "Highway", isDark: true, accentColor: "#006bb3" },
  { id: "hipster-green", name: "Hipster Green", isDark: true, accentColor: "#246eb2" },
  { id: "hivacruz", name: "Hivacruz", isDark: true, accentColor: "#3d8fd1" },
  { id: "homebrew", name: "Homebrew", isDark: true, accentColor: "#0d0dbf" },
  { id: "hopscotch", name: "Hopscotch", isDark: true, accentColor: "#1290bf" },
  { id: "hopscotch-256", name: "Hopscotch.256", isDark: true, accentColor: "#1290bf" },
  { id: "horizon", name: "Horizon", isDark: true, accentColor: "#26bbd9" },
  { id: "horizon-bright", name: "Horizon Bright", isDark: false, accentColor: "#00bedd" },
  { id: "hot-dog-stand", name: "Hot Dog Stand", isDark: true, accentColor: "#000000" },
  { id: "hot-dog-stand-mustard", name: "Hot Dog Stand (Mustard)", isDark: false, accentColor: "#000000" },
  { id: "hurtado", name: "Hurtado", isDark: true, accentColor: "#496487" },
  { id: "hybrid", name: "Hybrid", isDark: true, accentColor: "#6e90b0" },
  { id: "ibm-5153-cga", name: "IBM 5153 CGA", isDark: true, accentColor: "#3333db" },
  { id: "ibm-5153-cga-black", name: "IBM 5153 CGA (Black)", isDark: true, accentColor: "#0000c4" },
  { id: "ic-green-ppl", name: "IC Green PPL", isDark: true, accentColor: "#2ec3b9" },
  { id: "ic-orange-ppl", name: "IC Orange PPL", isDark: true, accentColor: "#bd6d00" },
  { id: "ir-black", name: "IR Black", isDark: true, accentColor: "#96cafe" },
  { id: "irix-console", name: "IRIX Console", isDark: true, accentColor: "#0739e2" },
  { id: "irix-terminal", name: "IRIX Terminal", isDark: true, accentColor: "#0004ff" },
  { id: "iceberg-dark", name: "Iceberg Dark", isDark: true, accentColor: "#84a0c6" },
  { id: "iceberg-light", name: "Iceberg Light", isDark: false, accentColor: "#2d539e" },
  { id: "idea", name: "Idea", isDark: true, accentColor: "#437ee7" },
  { id: "idle-toes", name: "Idle Toes", isDark: true, accentColor: "#4099ff" },
  { id: "jackie-brown", name: "Jackie Brown", isDark: true, accentColor: "#246eb2" },
  { id: "japanesque", name: "Japanesque", isDark: true, accentColor: "#4c9ad4" },
  { id: "jellybeans", name: "Jellybeans", isDark: true, accentColor: "#97bedc" },
  { id: "jetbrains-darcula", name: "JetBrains Darcula", isDark: true, accentColor: "#4581eb" },
  { id: "jubi", name: "Jubi", isDark: true, accentColor: "#576ea6" },
  { id: "kanagawa-dragon", name: "Kanagawa Dragon", isDark: true, accentColor: "#8ba4b0" },
  { id: "kanagawa-wave", name: "Kanagawa Wave", isDark: true, accentColor: "#7e9cd8" },
  { id: "kanagawabones", name: "Kanagawabones", isDark: true, accentColor: "#7eb3c9" },
  { id: "kibble", name: "Kibble", isDark: true, accentColor: "#3449d1" },
  { id: "kitty-default", name: "Kitty Default", isDark: true, accentColor: "#0d73cc" },
  { id: "kitty-low-contrast", name: "Kitty Low Contrast", isDark: true, accentColor: "#0d73cc" },
  { id: "kolorit", name: "Kolorit", isDark: true, accentColor: "#5db4ee" },
  { id: "konsolas", name: "Konsolas", isDark: true, accentColor: "#2323a5" },
  { id: "kurokula", name: "Kurokula", isDark: true, accentColor: "#5c91dd" },
  { id: "lab-fox", name: "Lab Fox", isDark: true, accentColor: "#db3b21" },
  { id: "laser", name: "Laser", isDark: true, accentColor: "#fed300" },
  { id: "later-this-evening", name: "Later This Evening", isDark: true, accentColor: "#a0bad6" },
  { id: "lavandula", name: "Lavandula", isDark: true, accentColor: "#4f4a7f" },
  { id: "light-owl", name: "Light Owl", isDark: false, accentColor: "#288ed7" },
  { id: "liquid-carbon", name: "Liquid Carbon", isDark: true, accentColor: "#0099cc" },
  { id: "liquid-carbon-transparent", name: "Liquid Carbon Transparent", isDark: true, accentColor: "#0099cc" },
  { id: "lovelace", name: "Lovelace", isDark: true, accentColor: "#8897f4" },
  { id: "man-page", name: "Man Page", isDark: false, accentColor: "#0000b2" },
  { id: "mariana", name: "Mariana", isDark: true, accentColor: "#6699cc" },
  { id: "material", name: "Material", isDark: false, accentColor: "#134eb2" },
  { id: "material-dark", name: "Material Dark", isDark: true, accentColor: "#134eb2" },
  { id: "material-darker", name: "Material Darker", isDark: true, accentColor: "#82aaff" },
  { id: "material-design-colors", name: "Material Design Colors", isDark: true, accentColor: "#37b6ff" },
  { id: "material-ocean", name: "Material Ocean", isDark: true, accentColor: "#82aaff" },
  { id: "mathias", name: "Mathias", isDark: true, accentColor: "#c48dff" },
  { id: "matrix", name: "Matrix", isDark: true, accentColor: "#3f5242" },
  { id: "matte-black", name: "Matte Black", isDark: true, accentColor: "#e68e0d" },
  { id: "medallion", name: "Medallion", isDark: true, accentColor: "#616bb0" },
  { id: "melange-dark", name: "Melange Dark", isDark: true, accentColor: "#7f91b2" },
  { id: "melange-light", name: "Melange Light", isDark: false, accentColor: "#7892bd" },
  { id: "mellifluous", name: "Mellifluous", isDark: true, accentColor: "#a8a1be" },
  { id: "mellow", name: "Mellow", isDark: true, accentColor: "#aca1cf" },
  { id: "miasma", name: "Miasma", isDark: true, accentColor: "#78824b" },
  { id: "midnight-in-mojave", name: "Midnight In Mojave", isDark: true, accentColor: "#0a84ff" },
  { id: "mirage", name: "Mirage", isDark: true, accentColor: "#7fb5ff" },
  { id: "misterioso", name: "Misterioso", isDark: true, accentColor: "#338f86" },
  { id: "molokai", name: "Molokai", isDark: true, accentColor: "#1080d0" },
  { id: "mona-lisa", name: "Mona Lisa", isDark: true, accentColor: "#515c5d" },
  { id: "monokai-classic", name: "Monokai Classic", isDark: true, accentColor: "#fd971f" },
  { id: "monokai-pro", name: "Monokai Pro", isDark: true, accentColor: "#fc9867" },
  { id: "monokai-pro-light", name: "Monokai Pro Light", isDark: false, accentColor: "#e16032" },
  { id: "monokai-pro-light-sun", name: "Monokai Pro Light Sun", isDark: false, accentColor: "#d4572b" },
  { id: "monokai-pro-machine", name: "Monokai Pro Machine", isDark: true, accentColor: "#ffb270" },
  { id: "monokai-pro-octagon", name: "Monokai Pro Octagon", isDark: true, accentColor: "#ff9b5e" },
  { id: "monokai-pro-ristretto", name: "Monokai Pro Ristretto", isDark: true, accentColor: "#f38d70" },
  { id: "monokai-pro-spectrum", name: "Monokai Pro Spectrum", isDark: true, accentColor: "#fd9353" },
  { id: "monokai-remastered", name: "Monokai Remastered", isDark: true, accentColor: "#9d65ff" },
  { id: "monokai-soda", name: "Monokai Soda", isDark: true, accentColor: "#9d65ff" },
  { id: "monokai-vivid", name: "Monokai Vivid", isDark: true, accentColor: "#0443ff" },
  { id: "moonfly", name: "Moonfly", isDark: true, accentColor: "#80a0ff" },
  { id: "n0tch2k", name: "N0Tch2K", isDark: true, accentColor: "#657d3e" },
  { id: "neobones-dark", name: "Neobones Dark", isDark: true, accentColor: "#8190d4" },
  { id: "neobones-light", name: "Neobones Light", isDark: false, accentColor: "#286486" },
  { id: "neon", name: "Neon", isDark: true, accentColor: "#0f15d8" },
  { id: "neopolitan", name: "Neopolitan", isDark: true, accentColor: "#324883" },
  { id: "neutron", name: "Neutron", isDark: true, accentColor: "#6a7c93" },
  { id: "night-lion-v1", name: "Night Lion V1", isDark: true, accentColor: "#276bd8" },
  { id: "night-lion-v2", name: "Night Lion V2", isDark: true, accentColor: "#64d0f0" },
  { id: "night-owl", name: "Night Owl", isDark: true, accentColor: "#82aaff" },
  { id: "night-owlish-light", name: "Night Owlish Light", isDark: false, accentColor: "#4876d6" },
  { id: "nightfox", name: "Nightfox", isDark: true, accentColor: "#719cd6" },
  { id: "niji", name: "Niji", isDark: true, accentColor: "#2ab9ff" },
  { id: "nocturnal-winter", name: "Nocturnal Winter", isDark: true, accentColor: "#3182e0" },
  { id: "nord", name: "Nord", isDark: true, accentColor: "#81a1c1" },
  { id: "nord-light", name: "Nord Light", isDark: false, accentColor: "#81a1c1" },
  { id: "nord-wave", name: "Nord Wave", isDark: true, accentColor: "#81a1c1" },
  { id: "nordfox", name: "Nordfox", isDark: true, accentColor: "#81a1c1" },
  { id: "novel", name: "Novel", isDark: false, accentColor: "#0000cc" },
  { id: "nvim-dark", name: "Nvim Dark", isDark: true, accentColor: "#a6dbff" },
  { id: "nvim-light", name: "Nvim Light", isDark: false, accentColor: "#004c73" },
  { id: "obsidian", name: "Obsidian", isDark: true, accentColor: "#3a9bdb" },
  { id: "ocean", name: "Ocean", isDark: true, accentColor: "#0000b2" },
  { id: "oceanic-material", name: "Oceanic Material", isDark: true, accentColor: "#1e80f0" },
  { id: "oceanic-next", name: "Oceanic Next", isDark: true, accentColor: "#6699cc" },
  { id: "ollie", name: "Ollie", isDark: true, accentColor: "#2d57ac" },
  { id: "one-double-dark", name: "One Double Dark", isDark: true, accentColor: "#3fb1f5" },
  { id: "one-double-light", name: "One Double Light", isDark: false, accentColor: "#0087c1" },
  { id: "one-half-dark", name: "One Half Dark", isDark: true, accentColor: "#61afef" },
  { id: "one-half-light", name: "One Half Light", isDark: false, accentColor: "#0184bc" },
  { id: "operator-mono-dark", name: "Operator Mono Dark", isDark: true, accentColor: "#4387cf" },
  { id: "overnight-slumber", name: "Overnight Slumber", isDark: true, accentColor: "#8dabe1" },
  { id: "oxocarbon", name: "Oxocarbon", isDark: true, accentColor: "#00c15a" },
  { id: "pale-night-hc", name: "Pale Night Hc", isDark: true, accentColor: "#82aaff" },
  { id: "pandora", name: "Pandora", isDark: true, accentColor: "#338f86" },
  { id: "paraiso-dark", name: "Paraiso Dark", isDark: true, accentColor: "#06b6ef" },
  { id: "paul-millr", name: "Paul Millr", isDark: true, accentColor: "#396bd7" },
  { id: "pencil-dark", name: "Pencil Dark", isDark: true, accentColor: "#008ec4" },
  { id: "pencil-light", name: "Pencil Light", isDark: false, accentColor: "#008ec4" },
  { id: "peppermint", name: "Peppermint", isDark: true, accentColor: "#449fd0" },
  { id: "phala-green-dark", name: "Phala Green Dark", isDark: true, accentColor: "#0223c0" },
  { id: "piatto-light", name: "Piatto Light", isDark: false, accentColor: "#3c5ea8" },
  { id: "pnevma", name: "Pnevma", isDark: true, accentColor: "#7fa5bd" },
  { id: "popping-and-locking", name: "Popping And Locking", isDark: true, accentColor: "#458588" },
  { id: "powershell", name: "Powershell", isDark: true, accentColor: "#403fc2" },
  { id: "primary", name: "Primary", isDark: false, accentColor: "#4285f4" },
  { id: "pro", name: "Pro", isDark: true, accentColor: "#2009db" },
  { id: "pro-light", name: "Pro Light", isDark: false, accentColor: "#3b75ff" },
  { id: "purple-rain", name: "Purple Rain", isDark: true, accentColor: "#00a2fa" },
  { id: "purplepeter", name: "Purplepeter", isDark: true, accentColor: "#66d9ef" },
  { id: "rapture", name: "Rapture", isDark: true, accentColor: "#6c9bf5" },
  { id: "raycast-dark", name: "Raycast Dark", isDark: true, accentColor: "#56c2ff" },
  { id: "raycast-light", name: "Raycast Light", isDark: false, accentColor: "#138af2" },
  { id: "rebecca", name: "Rebecca", isDark: true, accentColor: "#7aa5ff" },
  { id: "red-alert", name: "Red Alert", isDark: true, accentColor: "#489bee" },
  { id: "red-planet", name: "Red Planet", isDark: true, accentColor: "#69819e" },
  { id: "red-sands", name: "Red Sands", isDark: true, accentColor: "#0072ff" },
  { id: "relaxed", name: "Relaxed", isDark: true, accentColor: "#6a8799" },
  { id: "retro", name: "Retro", isDark: true, accentColor: "#13a10e" },
  { id: "retro-legends", name: "Retro Legends", isDark: true, accentColor: "#4066f2" },
  { id: "rippedcasts", name: "Rippedcasts", isDark: true, accentColor: "#75a5b0" },
  { id: "rose-pine", name: "Rose Pine", isDark: true, accentColor: "#9ccfd8" },
  { id: "rose-pine-dawn", name: "Rose Pine Dawn", isDark: false, accentColor: "#56949f" },
  { id: "rose-pine-moon", name: "Rose Pine Moon", isDark: true, accentColor: "#9ccfd8" },
  { id: "rouge-2", name: "Rouge 2", isDark: true, accentColor: "#6e94b9" },
  { id: "royal", name: "Royal", isDark: true, accentColor: "#6580b0" },
  { id: "ryuuko", name: "Ryuuko", isDark: true, accentColor: "#6a8e95" },
  { id: "sakura", name: "Sakura", isDark: true, accentColor: "#6964ab" },
  { id: "scarlet-protocol", name: "Scarlet Protocol", isDark: true, accentColor: "#0271b6" },
  { id: "sea-shells", name: "Sea Shells", isDark: true, accentColor: "#1e4950" },
  { id: "seafoam-pastel", name: "Seafoam Pastel", isDark: true, accentColor: "#4d7b82" },
  { id: "selenized-dark", name: "Selenized Dark", isDark: true, accentColor: "#4695f7" },
  { id: "selenized-light", name: "Selenized Light", isDark: false, accentColor: "#0072d4" },
  { id: "seoulbones-dark", name: "Seoulbones Dark", isDark: true, accentColor: "#97bdde" },
  { id: "seoulbones-light", name: "Seoulbones Light", isDark: false, accentColor: "#0084a3" },
  { id: "seti", name: "Seti", isDark: true, accentColor: "#43a5d5" },
  { id: "shades-of-purple", name: "Shades Of Purple", isDark: true, accentColor: "#6943ff" },
  { id: "shaman", name: "Shaman", isDark: true, accentColor: "#449a86" },
  { id: "slate", name: "Slate", isDark: true, accentColor: "#325856" },
  { id: "sleepy-hollow", name: "Sleepy Hollow", isDark: true, accentColor: "#5f63b4" },
  { id: "smyck", name: "Smyck", isDark: true, accentColor: "#62a3c4" },
  { id: "snazzy", name: "Snazzy", isDark: true, accentColor: "#49baff" },
  { id: "snazzy-soft", name: "Snazzy Soft", isDark: true, accentColor: "#57c7ff" },
  { id: "soft-server", name: "Soft Server", isDark: true, accentColor: "#6b8fa3" },
  { id: "solarized-darcula", name: "Solarized Darcula", isDark: true, accentColor: "#2075c7" },
  { id: "solarized-dark-higher-contrast", name: "Solarized Dark Higher Contrast", isDark: true, accentColor: "#2176c7" },
  { id: "solarized-dark-patched", name: "Solarized Dark Patched", isDark: true, accentColor: "#2176c7" },
  { id: "solarized-osaka-night", name: "Solarized Osaka Night", isDark: true, accentColor: "#7aa2f7" },
  { id: "sonokai", name: "Sonokai", isDark: true, accentColor: "#76cce0" },
  { id: "spacedust", name: "Spacedust", isDark: true, accentColor: "#0f548b" },
  { id: "spacegray", name: "Spacegray", isDark: true, accentColor: "#7d8fa4" },
  { id: "spacegray-bright", name: "Spacegray Bright", isDark: true, accentColor: "#7baec1" },
  { id: "spacegray-eighties", name: "Spacegray Eighties", isDark: true, accentColor: "#5486c0" },
  { id: "spacegray-eighties-dull", name: "Spacegray Eighties Dull", isDark: true, accentColor: "#7c8fa5" },
  { id: "spiderman", name: "Spiderman", isDark: true, accentColor: "#2c3fff" },
  { id: "spring", name: "Spring", isDark: false, accentColor: "#1dd3ee" },
  { id: "square", name: "Square", isDark: true, accentColor: "#a9cdeb" },
  { id: "squirrelsong-dark", name: "Squirrelsong Dark", isDark: true, accentColor: "#4395c6" },
  { id: "srcery", name: "Srcery", isDark: true, accentColor: "#2c78bf" },
  { id: "starlight", name: "Starlight", isDark: true, accentColor: "#24acd4" },
  { id: "sublette", name: "Sublette", isDark: true, accentColor: "#5588ff" },
  { id: "subliminal", name: "Subliminal", isDark: true, accentColor: "#6699cc" },
  { id: "sugarplum", name: "Sugarplum", isDark: true, accentColor: "#db7ddd" },
  { id: "sundried", name: "Sundried", isDark: true, accentColor: "#485b98" },
  { id: "symfonic", name: "Symfonic", isDark: true, accentColor: "#0084d4" },
  { id: "synthwave", name: "Synthwave", isDark: true, accentColor: "#2186ec" },
  { id: "synthwave-alpha", name: "Synthwave Alpha", isDark: true, accentColor: "#6e29ad" },
  { id: "synthwave-everything", name: "Synthwave Everything", isDark: true, accentColor: "#6d77b3" },
  { id: "tango-adapted", name: "Tango Adapted", isDark: false, accentColor: "#00a2ff" },
  { id: "tango-half-adapted", name: "Tango Half Adapted", isDark: false, accentColor: "#008ef6" },
  { id: "tearout", name: "Tearout", isDark: true, accentColor: "#b5955e" },
  { id: "teerb", name: "Teerb", isDark: true, accentColor: "#86aed6" },
  { id: "terafox", name: "Terafox", isDark: true, accentColor: "#5a93aa" },
  { id: "terminal-basic", name: "Terminal Basic", isDark: false, accentColor: "#0000b2" },
  { id: "terminal-basic-dark", name: "Terminal Basic Dark", isDark: true, accentColor: "#6444ed" },
  { id: "thayer-bright", name: "Thayer Bright", isDark: true, accentColor: "#2757d6" },
  { id: "the-hulk", name: "The Hulk", isDark: true, accentColor: "#2525f5" },
  { id: "tinacious-design-dark", name: "Tinacious Design Dark", isDark: true, accentColor: "#00cbff" },
  { id: "tinacious-design-light", name: "Tinacious Design Light", isDark: false, accentColor: "#00cbff" },
  { id: "tokyonight", name: "TokyoNight", isDark: true, accentColor: "#7aa2f7" },
  { id: "tokyonight-day", name: "TokyoNight Day", isDark: false, accentColor: "#2e7de9" },
  { id: "tokyonight-moon", name: "TokyoNight Moon", isDark: true, accentColor: "#82aaff" },
  { id: "tokyonight-night", name: "TokyoNight Night", isDark: true, accentColor: "#7aa2f7" },
  { id: "tokyonight-storm", name: "TokyoNight Storm", isDark: true, accentColor: "#7aa2f7" },
  { id: "tomorrow", name: "Tomorrow", isDark: false, accentColor: "#4271ae" },
  { id: "tomorrow-night", name: "Tomorrow Night", isDark: true, accentColor: "#81a2be" },
  { id: "tomorrow-night-blue", name: "Tomorrow Night Blue", isDark: true, accentColor: "#bbdaff" },
  { id: "tomorrow-night-bright", name: "Tomorrow Night Bright", isDark: true, accentColor: "#7aa6da" },
  { id: "tomorrow-night-burns", name: "Tomorrow Night Burns", isDark: true, accentColor: "#fc595f" },
  { id: "tomorrow-night-eighties", name: "Tomorrow Night Eighties", isDark: true, accentColor: "#6699cc" },
  { id: "toy-chest", name: "Toy Chest", isDark: true, accentColor: "#325d96" },
  { id: "treehouse", name: "Treehouse", isDark: true, accentColor: "#58859a" },
  { id: "twilight", name: "Twilight", isDark: true, accentColor: "#44474a" },
  { id: "ubuntu", name: "Ubuntu", isDark: true, accentColor: "#3465a4" },
  { id: "ultra-dark", name: "Ultra Dark", isDark: true, accentColor: "#82aaff" },
  { id: "ultra-violent", name: "Ultra Violent", isDark: true, accentColor: "#47e0fb" },
  { id: "under-the-sea", name: "Under The Sea", isDark: true, accentColor: "#459a86" },
  { id: "unikitty", name: "Unikitty", isDark: true, accentColor: "#145fcd" },
  { id: "urple", name: "Urple", isDark: true, accentColor: "#564d9b" },
  { id: "vague", name: "Vague", isDark: true, accentColor: "#7e98e8" },
  { id: "vaughn", name: "Vaughn", isDark: true, accentColor: "#5555ff" },
  { id: "vercel", name: "Vercel", isDark: true, accentColor: "#006aff" },
  { id: "vesper", name: "Vesper", isDark: true, accentColor: "#aca1cf" },
  { id: "vibrant-ink", name: "Vibrant Ink", isDark: true, accentColor: "#44b4cc" },
  { id: "vimbones", name: "Vimbones", isDark: false, accentColor: "#286486" },
  { id: "violet-dark", name: "Violet Dark", isDark: true, accentColor: "#2e8bce" },
  { id: "violet-light", name: "Violet Light", isDark: false, accentColor: "#2e8bce" },
  { id: "violite", name: "Violite", isDark: true, accentColor: "#a979ec" },
  { id: "warm-neon", name: "Warm Neon", isDark: true, accentColor: "#4261c5" },
  { id: "wez", name: "Wez", isDark: true, accentColor: "#5555cc" },
  { id: "whimsy", name: "Whimsy", isDark: true, accentColor: "#65aef7" },
  { id: "wild-cherry", name: "Wild Cherry", isDark: true, accentColor: "#883cdc" },
  { id: "wilmersdorf", name: "Wilmersdorf", isDark: true, accentColor: "#a6c1e0" },
  { id: "wombat", name: "Wombat", isDark: true, accentColor: "#5da9f6" },
  { id: "wryan", name: "Wryan", isDark: true, accentColor: "#395573" },
  { id: "xcode-dark", name: "Xcode Dark", isDark: true, accentColor: "#4eb0cc" },
  { id: "xcode-dark-hc", name: "Xcode Dark hc", isDark: true, accentColor: "#4ec4e6" },
  { id: "xcode-light", name: "Xcode Light", isDark: false, accentColor: "#0f68a0" },
  { id: "xcode-light-hc", name: "Xcode Light hc", isDark: false, accentColor: "#0058a1" },
  { id: "xcode-wwdc", name: "Xcode WWDC", isDark: true, accentColor: "#8884c5" },
  { id: "zenbones", name: "Zenbones", isDark: false, accentColor: "#286486" },
  { id: "zenbones-dark", name: "Zenbones Dark", isDark: true, accentColor: "#6099c0" },
  { id: "zenbones-light", name: "Zenbones Light", isDark: false, accentColor: "#286486" },
  { id: "zenburn", name: "Zenburn", isDark: true, accentColor: "#5d6d7d" },
  { id: "zenburned", name: "Zenburned", isDark: true, accentColor: "#6099c0" },
  { id: "zenwritten-dark", name: "Zenwritten Dark", isDark: true, accentColor: "#6099c0" },
  { id: "zenwritten-light", name: "Zenwritten Light", isDark: false, accentColor: "#286486" },
  { id: "iterm2-dark-background", name: "iTerm2 Dark Background", isDark: true, accentColor: "#0225c7" },
  { id: "iterm2-default", name: "iTerm2 Default", isDark: true, accentColor: "#2225c4" },
  { id: "iterm2-light-background", name: "iTerm2 Light Background", isDark: false, accentColor: "#0225c7" },
  { id: "iterm2-pastel-dark-background", name: "iTerm2 Pastel Dark Background", isDark: true, accentColor: "#a5d5fe" },
  { id: "iterm2-smoooooth", name: "iTerm2 Smoooooth", isDark: true, accentColor: "#2744c7" },
  { id: "iterm2-solarized-dark", name: "iTerm2 Solarized Dark", isDark: true, accentColor: "#268bd2" },
  { id: "iterm2-solarized-light", name: "iTerm2 Solarized Light", isDark: false, accentColor: "#268bd2" },
  { id: "iterm2-tango-dark", name: "iTerm2 Tango Dark", isDark: true, accentColor: "#427ab3" },
  { id: "iterm2-tango-light", name: "iTerm2 Tango Light", isDark: false, accentColor: "#427ab3" },
];

function applyThemeToDocument(theme: Theme, isPreview = false): void {
  document.documentElement.setAttribute("data-theme", theme.id);

  if (!isPreview) {
    try {
      localStorage.setItem("typehere-theme-cache", theme.id);
    } catch {}
  }
}

function restoreThemeFromCache(): boolean {
  try {
    const cached = localStorage.getItem("typehere-theme-cache");
    if (!cached) return false;

    if (cached.startsWith("{")) {
      const parsed = JSON.parse(cached) as { id: string };
      if (parsed.id) {
        localStorage.setItem("typehere-theme-cache", parsed.id);
        document.documentElement.setAttribute("data-theme", parsed.id);
        return true;
      }
      return false;
    }

    document.documentElement.setAttribute("data-theme", cached);
    return true;
  } catch {
    return false;
  }
}

function getThemeById(id: string): Theme {
  return THEMES.find((t) => t.id === id) ?? THEMES[0];
}

const RECOMMENDED_THEME_IDS = [
  "typehere-dark",
  "catppuccin-mocha",
  "tokyonight-night",
  "rose-pine-moon",
  "github-dark-default",
  "nord",
] as const;

function getRecommendedThemes(): Theme[] {
  return RECOMMENDED_THEME_IDS.map((id) => getThemeById(id));
}

export type { Theme };
export { THEMES, RECOMMENDED_THEME_IDS, applyThemeToDocument, restoreThemeFromCache, getThemeById, getRecommendedThemes };
